### ISSUE TITLE
Trajs / Logs links lead to 404

### ISSUE THREAD

**Issue by 0xdevalias** [SWE-bench/swe-bench.github.io#1]
On https://www.swebench.com/ , it seems that all of the 'Trajs' links in the tables lead to a 404:

- https://www.swebench.com/test/20240402_sweagent_gpt4/trajs
- https://www.swebench.com/test/20240402_sweagent_claude3opus/trajs
- https://www.swebench.com/lite/20240402_sweagent_gpt4/trajs
- https://www.swebench.com/lite/20240402_sweagent_claude3opus/trajs

And seemingly all of the 'Logs' links for the lite leaderboard also lead to 404:

- https://www.swebench.com/lite/20240523_aider/logs
- https://www.swebench.com/lite/20240524_20240524_opencsg_starship_gpt4/logs
- https://www.swebench.com/lite/20240402_sweagent_gpt4/logs
- https://www.swebench.com/lite/20240402_rag_claude3opus/logs
- https://www.swebench.com/lite/20231010_rag_claude2/logs
- https://www.swebench.com/lite/20240402_rag_gpt4/logs
- https://www.swebench.com/lite/20231010_rag_swellama7b/logs
- https://www.swebench.com/lite/20231010_rag_swellama13b/logs
- https://www.swebench.com/lite/20231010_rag_gpt35/logs

**Comment by john-b-yang** [comment]
@0xdevalias thanks for the catch! Apologies about the late response - this should be fixed now? It originally was a problem with how the `href` values were being defined.

**Comment by 0xdevalias** [comment]
> this should be fixed now?

@john-b-yang In both tables, all 'Trajs' and most 'Logs' links seem to work now; thanks! :)

The following still seems broken though:

- https://github.com/swe-bench/experiments/tree/main/evaluation/lite/20240527_20240527_marscode-agent-dev/logs

Presumably it's meant to be:

- https://github.com/swe-bench/experiments/tree/main/evaluation/lite/20240527_marscode-agent-dev/logs

**Comment by john-b-yang** [comment]
@0xdevalias Ah thank you so much for the catch! Just fixed it!

Closing this issue, really appreciate the help with double checking the links. Feel free to re-open if anything else is broken 😄

**Comment by 0xdevalias** [comment]
> Feel free to re-open if anything else is broken

@john-b-yang Is the fix of that link I mentioned above deployed yet? As it still seems broken when I checked just now.

**Comment by john-b-yang** [comment]
Ah the deployment is not working for reason, will look into it today.

**Comment by john-b-yang** [comment]
Ok it should be working now! Not sure why deployment wasn't working Friday, but it worked today.

**Comment by 0xdevalias** [comment]
Just re-checked, that link is fixed now, so looks good!

**Comment by john-b-yang** [comment]
Sweet, thanks a bunch again @0xdevalias!
